version: 2
updates:
    - package-ecosystem: "docker"
      directory: "/"
      open-pull-requests-limit: 3
      schedule:
          interval: "daily" # Note: only weekdays: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#scheduleinterval.
          time: "08:00" # Note: UTC.

    - package-ecosystem: "docker"
      directory: "/etc/build/"
      open-pull-requests-limit: 1 # Note: only one docker dependency.
      schedule:
          interval: "daily" # Note: only weekdays: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#scheduleinterval.
          time: "08:00" # Note: UTC.

    - package-ecosystem: "docker"
      directory: "/etc/docker/uiproxy/"
      open-pull-requests-limit: 1 # Note: only one docker dependency.
      schedule:
          interval: "daily" # Note: only weekdays: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#scheduleinterval.
          time: "08:00" # Note: UTC.

    - package-ecosystem: "github-actions"
      directory: "/" # Note: .== github/workflows: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#directory.
      open-pull-requests-limit: 2
      schedule:
          interval: "daily" # Note: only weekdays: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#scheduleinterval.
          time: "08:00" # Note: UTC.

    - package-ecosystem: "gomod"
      directory: "/"
      open-pull-requests-limit: 3 # Note: >100 dependencies, trying not to overwhelm the CI.
      schedule:
          interval: "daily" # Note: only weekdays: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#scheduleinterval.
          time: "08:00" # Note: UTC.

    - package-ecosystem: "gomod"
      directory: "/pkg/sdk/"
      open-pull-requests-limit: 2 # Note: >10 dependencies, trying not to overwhelm the CI.
      schedule:
          interval: "daily" # Note: only weekdays: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#scheduleinterval.
          time: "08:00" # Note: UTC.
